/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ScheduleReactivation': EventHandler<{ memoryId: string; embeddingId: string; timestamp: string }, { topic: 'memory-reactivation-scheduled'; data: { memoryId: string; scheduledFor: string; delayMs?: number; immediate?: boolean } }>
    'ReactivateMemory': EventHandler<{ memoryId: string; scheduledFor: string; delayMs?: number; immediate?: boolean }, { topic: 'memory-reactivated'; data: { memoryId: string; title: string; reanalysis: string; reactivatedAt: string } }>
    'NotifyUser': EventHandler<{ memoryId: string; title: string; reanalysis: string; reactivatedAt: string }, never>
    'EmbedMemory': EventHandler<{ memoryId: string; analysis: { summary: string; category: string; rootCause?: string; lessons: Array<string> }; timestamp: string }, { topic: 'memory-embedded'; data: { memoryId: string; embeddingId: string; timestamp: string } }>
    'AnalyzeAI': EventHandler<{ memoryId: string; title: string; type: string }, { topic: 'memory-analyzed'; data: { memoryId: string; analysis: { summary: string; category: string; rootCause?: string; lessons: Array<string> }; timestamp: string } }>
    'UpdateMemory': ApiRouteHandler<{ title?: string; description?: string; type?: 'future' | 'decision' | 'failure' | 'context'; tags?: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; status?: 'active' | 'scheduled' | 'triggered' | 'archived' }, ApiResponse<200, { id: string; title: string; description: string; type: 'future' | 'decision' | 'failure' | 'context'; tags: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; triggerType: 'date' | 'event' | 'manual'; triggerDate?: string; triggerEvent?: string; userId: string; teamId: string; aiSummary?: string; aiCategory?: string; rootCause?: string; keyLessons?: Array<string>; status: 'active' | 'scheduled' | 'triggered' | 'archived'; createdAt: string; updatedAt: string; triggeredAt?: string; embeddingId?: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'SearchMemories': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { memories: Array<{ id: string; title: string; description: string; type: 'future' | 'decision' | 'failure' | 'context'; tags: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; triggerType: 'date' | 'event' | 'manual'; triggerDate?: string; triggerEvent?: string; userId: string; teamId: string; aiSummary?: string; aiCategory?: string; rootCause?: string; keyLessons?: Array<string>; status: 'active' | 'scheduled' | 'triggered' | 'archived'; createdAt: string; updatedAt: string; triggeredAt?: string; embeddingId?: string }>; count: number }>, never>
    'LogMemory': ApiRouteHandler<{ title: string; description: string; type: 'future' | 'decision' | 'failure' | 'context'; tags: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; triggerType: 'date' | 'event' | 'manual'; triggerDate?: string; triggerEvent?: string; userId: string; teamId: string }, ApiResponse<201, { id: string; title: string; description: string; type: 'future' | 'decision' | 'failure' | 'context'; tags: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; triggerType: 'date' | 'event' | 'manual'; triggerDate?: string; triggerEvent?: string; userId: string; teamId: string; aiSummary?: string; aiCategory?: string; rootCause?: string; keyLessons?: Array<string>; status: 'active' | 'scheduled' | 'triggered' | 'archived'; createdAt: string; updatedAt: string; triggeredAt?: string; embeddingId?: string }> | ApiResponse<400, { error: string }>, { topic: 'memory-created'; data: { memoryId: string; title: string; type: string } }>
    'GetMemory': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; title: string; description: string; type: 'future' | 'decision' | 'failure' | 'context'; tags: Array<string>; severity?: 'low' | 'medium' | 'high' | 'critical'; triggerType: 'date' | 'event' | 'manual'; triggerDate?: string; triggerEvent?: string; userId: string; teamId: string; aiSummary?: string; aiCategory?: string; rootCause?: string; keyLessons?: Array<string>; status: 'active' | 'scheduled' | 'triggered' | 'archived'; createdAt: string; updatedAt: string; triggeredAt?: string; embeddingId?: string }> | ApiResponse<404, { error: string }>, never>
    'AnswerQuestion': ApiRouteHandler<{ question: string; teamId: string; limit: number }, ApiResponse<200, { answer: string; sources: Array<{ memoryId: string; title: string; relevance: number }> }> | ApiResponse<400, { error: string }>, never>
  }
    
}